#! /bin/sh

FILE=xpianoRes.m5.FIL.sdif

sleep 1  # Wait one second
echo 
echo \****************************
echo "***  Test on selection  ***"
echo \****************************
echo

../tools/querysdif/querysdif $FILE -t ../data/SdifTypes.STYP
echo
echo Waiting for output: Found 1REB frame, index 0.
./testcheck $FILE 1REB
echo
echo Waiting for output: Found 1REB frame, index 1. 
./testcheck $FILE 1NOI 1REB
echo
echo Waiting for output: Found no frame, index -1.
./testcheck $FILE 1HRM 1HRM 1HRM
echo
