# $Id: Makefile.src,v 2.1 1998-12-21 18:28:03 schwarz Exp $
#
#               Copyright (c) 1998 by IRCAM - Centre Pompidou
#                          All rights reserved.
#
#  For any information regarding this and other IRCAM software, please
#  send email to:
#                            manager@ircam.fr
#
#  src tosdif




SRC = test.c
