# $Id: Makefile.postamble,v 2.1 1998-12-03 18:10:38 schwarz Exp $
#
# Makefile.postamble to be included after every makefile.
#
# $Log: not supported by cvs2svn $


$(SDIF_OBJ_DIR)/%.o: %.c
	@echo Compilation of $<
	@$(CC) $(CFLAGS) -o $@ -c $<

$(SDIF_LIB): $(SDIF_OBJS)
	@rm -f $(SDIF_LIB)
	ar r $(SDIF_LIB) $(SDIF_OBJS)
	if ( $(RANLIB) != 0 ) $(RANLIB) $@

 $(OUTDIRS) $(INSTALL_DIRS):
	mkdir -p $@



