# determine architecture
IF( NOT ARCH )
#   EXEC_PROGRAM(arch OUTPUT_VARIABLE ARCH RETURN_VALUE RES)
#   IF( RES GREATER 0)
#      EXEC_PROGRAM(uname ARGS -m OUTPUT_VARIABLE ARCH RETURN_VALUE RES)
#   ENDIF( RES GREATER 0)
#
#   IF( RES EQUAL 0)
#       MESSAGE("configure for architecture  ${ARCH}")
#   ELSE( RES EQUAL 0)
#       MESSAGE("Cannot determine ARCH")
#       ERROR()
#   ENDIF(RES EQUAL 0)
  SET(ARCH ${CMAKE_SYSTEM_PROCESSOR})
ENDIF(NOT ARCH )
MESSAGE("-- ARCH system is ${ARCH}")
