IF(APPLE)

  # only adjust sysroot if not cross compiling
  IF(NOT CMAKE_FIND_ROOT_PATH)  
    OPTION(DOUNIVERSAL "configure for cross compilation producing universal" OFF )
    IF(CMAKE_OSX_SYSROOT AND DOUNIVERSAL)
      IF(_CMAKE_OSX_MACHINE)
        IF("${_CMAKE_OSX_MACHINE}" STREQUAL "ppc")
          SET(CMAKE_OSX_ARCHITECTURES "ppc;i386" CACHE STRING "Build architectures for OSX" FORCE)
        ELSE("${_CMAKE_OSX_MACHINE}" STREQUAL "ppc")
          SET(CMAKE_OSX_ARCHITECTURES "i386;ppc" CACHE STRING "Build architectures for OSX" FORCE)
        ENDIF("${_CMAKE_OSX_MACHINE}" STREQUAL "ppc")
      ELSE(_CMAKE_OSX_MACHINE)
        SET( CMAKE_OSX_ARCHITECTURES  "ppc;i386" CACHE STRING "Build architectures for OSX" FORCE)
      ENDIF(_CMAKE_OSX_MACHINE)
    ELSE(CMAKE_OSX_SYSROOT AND DOUNIVERSAL)
      IF(DOUNIVERSAL)
        MESSAGE(FATAL_ERROR "Universal binaries can only created if the SDK MacOSX10.4u.sdk is installed")
      ENDIF(DOUNIVERSAL)
      IF(EXISTS /Developer/SDKs/MacOSX10.4u.sdk )
        IF(NOT "$ENV{CMAKE_OSX_SYSROOT}" STREQUAL "") 
          SET(SYSROOT "$ENV{CMAKE_OSX_SYSROOT}")
        ELSE(NOT "$ENV{CMAKE_OSX_SYSROOT}" STREQUAL "") 
          SET(SYSROOT MacOSX10.4u.sdk)          
        ENDIF(NOT "$ENV{CMAKE_OSX_SYSROOT}" STREQUAL "") 
        SET(CMAKE_OSX_SYSROOT "/Developer/SDKs/${SYSROOT}" CACHE STRING  "isysroot used for universal binary support" FORCE)
      ENDIF(EXISTS /Developer/SDKs/MacOSX10.4u.sdk )          
    ENDIF(CMAKE_OSX_SYSROOT AND DOUNIVERSAL)
  ENDIF(NOT CMAKE_FIND_ROOT_PATH) 
ENDIF(APPLE)
