IF ("${ARCH}" MATCHES "^p.*pc.*")
  FIND_PATH (SDK MacOSX10.3.9.sdk /Developer/SDKs DOC "Path to 10.3.9 SDK") 
  SET(MACOSX_DEPLOYMENT_TARGET 10.3 CACHE STRING "min macosx version to run on")
  IF (SDK)
    ADD_DEFINITIONS (-isysroot ${SDK}/MacOSX10.3.9.sdk)
  ENDIF (SDK)
ELSE ("${ARCH}" MATCHES "^p.*pc.*" )
  FIND_PATH (SDK MacOSX10.4u.sdk /Developer/SDKs DOC "Path to 10.4 SDK") 
  SET(MACOSX_DEPLOYMENT_TARGET 10.4 CACHE STRING "min macosx version to run on")
  IF(SDK)
    ADD_DEFINITIONS (-isysroot ${SDK}/MacOSX10.4u.sdk )
  ENDIF (SDK)    
ENDIF("${ARCH}" MATCHES "^p.*pc.*" )
IF(MACOSX_DEPLOYMENT_TARGET)
  ADD_DEFINITIONS (-mmacosx-version-min=${MACOSX_DEPLOYMENT_TARGET} )  
ENDIF(MACOSX_DEPLOYMENT_TARGET)
