# store the list of arguments
# in variable DOCFILES completing them with full path


MACRO (STORE_FILES_LIST STORE_VARIABLE INFILELIST )


SET(${STORE_VARIABLE})
FOREACH(FILE  ${INFILELIST} ${ARGN})
LIST(APPEND ${STORE_VARIABLE} ${CMAKE_CURRENT_SOURCE_DIR}/${FILE})
ENDFOREACH(FILE  ${INFILELIST})


ENDMACRO(STORE_FILES_LIST STORE_VARIABLE INFILELIST  )
